version: "2"

services:
  elixir:
    build: ./docker/elixir
    command: sh -c "mix phoenix.server"
    environment:
      - MIX_ENV=dev
    links:
      - postgres
    ports:
      - "4000:4000"
    volumes:
        - ./:/opt/app

  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: poniverse
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: "local"
